controllers/ReminderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Reminder;
use app\models\ReminderSearch;
use app\models\Next;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\base\Model;

class ReminderController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new ReminderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->setSort(['defaultOrder' => ['id'=>SORT_DESC]]);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
        $model = new Reminder();
        $today = date('Y-m-d');
        $model->load(Yii::$app->request->post());
        $model->next_date = date('Y-m-d', strtotime("+$model->permutation months", strtotime($today)));
        $model->date = $today;


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $today = date('Y-m-d');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Reminder::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionNext() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $service_id = $parents[0];
                $out = Next::getNextList($service_id);

                return json_encode(['output'=>$out, 'selected'=>'']);

            }
        }
        return json_encode(['output'=>'', 'selected'=>'']);
    }

        public function actionIndextoday()
        {
          $model = new Reminder;
          $today = date('Y-m-d');

          // $expression = new Expression('NOW()');
          $searchModel = ReminderSearch::find()->andFilterWhere(['like', 'next_date', $today]);

          $dataProvider = new ActiveDataProvider(['query' =>$searchModel,
          'sort' => ['attributes' => [

                             'id' => [

                                'default' => SORT_DESC
                             ],
                        ],],

                      ]);

          if(Yii::$app->request->post('hasEditable'))
          {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            if ($model->load($post))
            {
              $value = $model->status;
              return ['output'=> $value, 'message' => ''];

            }
            else {
              return ['otuput' => '', 'message' => ''];
            }

          }

          return $this->render('indextoday', [
              'searchModel' => $searchModel,
              'dataProvider' => $dataProvider,
              'today' =>  $today,
              'model' => $model,
          ]);
        }


        public function actionIndexweek()
        {
          $model = new Reminder;
          $today = date('Y-m-d');
          $week = date('Y-m-d', strtotime("+1 week", strtotime($today)));
          $searchModel = ReminderSearch::find()->andFilterWhere(['between', 'next_date', $today, $week]);
          $dataProvider = new ActiveDataProvider(['query' =>$searchModel,
          'sort' => ['attributes' => ['id' => ['default' => SORT_DESC]]]]);
          if(Yii::$app->request->post('hasEditable'))
          {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            if ($model->load($post))
            {
              $value = $model->status;
              return ['output'=> $value, 'message' => ''];
            }
            else {
              return ['otuput' => '', 'message' => ''];
            }

          }
          return $this->render('indexweek', [
              'searchModel' => $searchModel,
              'dataProvider' => $dataProvider,
              'today' =>  $today,
              'week' =>  $week,
              'model' => $model,
          ]);
        }


        public function actionCalendar()
        {
            $searchModel = new ReminderSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $dataProvider->setSort(['defaultOrder' => ['id'=>SORT_DESC]]);
            return $this->render('calendar', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }


}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">


    <?php
    NavBar::begin([
        'brandLabel' => '<img src="img/logo.jpg" class="img-responsive pull-left" width="48px">&nbsp;&nbsp;&nbsp;REFACCIONARIA Y SERVICIOS JUÁREZ',
        // 'brandLabel' => Yii::$app->name,

        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-fixed-top','style' => 'background-color: #fff;',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
        //     ['label' => 'Home', 'url' => ['/site/index']],
        //     ['label' => 'About', 'url' => ['/site/about']],
        //     ['label' => 'Contact', 'url' => ['/site/contact']],

            ['label' => 'Calendario', 'url' => ['/reminder/calendar']],
            ['label' => 'Recordatorios de la Semana', 'url' => ['/reminder/indexweek']],
            ['label' => 'Recordatorios para Hoy', 'url' => ['/reminder/indextoday']],
            ['label' => 'Servicios', 'url' => ['/reminder/index']],


            // Yii::$app->user->isGuest ? (
            //     ['label' => 'Login', 'url' => ['/site/login']]
            // ) : (
            //     '<li>'
            //     . Html::beginForm(['/site/logout'], 'post')
            //     . Html::submitButton(
            //         'Logout (' . Yii::$app->user->identity->username . ')',
            //         ['class' => 'btn btn-link logout']
            //     )
            //     . Html::endForm()
            //     . '</li>'
            // )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; 400tres.com <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>