models/Reminder.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "reminder".
 *
 * @property integer $id
 * @property string $customer
 * @property string $car
 * @property string $phone
 * @property string $service
 * @property string $date
 * @property string $next_date
 */
class Reminder extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reminder';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['car'], 'required'],
            [['permutation', 'test'], 'integer'],
            // [['next_date'], 'safe'],
            [['date', 'customer', 'car', 'phone', 'service', 'anotation'], 'string', 'max' => 60],
            [['next_date'], 'default', 'value' => null],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer' => 'Cliente',
            'car' => 'Automóvil',
            'phone' => 'Teléfono',
            'service' => 'Servicio',
            'date' => 'Fecha',
            'next_date' => 'Siguiente Servicio',
            'permutation' => '',
            'test' => '',
            'anotation' => 'Comentarios',
        ];
    }
}

controllers/ReminderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Reminder;
use app\models\ReminderSearch;
use app\models\Next;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\base\Model;

class ReminderController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new ReminderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->setSort(['defaultOrder' => ['id'=>SORT_DESC]]);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
        $model = new Reminder();
        $today = date('Y-m-d');
        $model->load(Yii::$app->request->post());
        $model->next_date = date('Y-m-d', strtotime("+$model->permutation months", strtotime($today)));
        $model->date = $today;


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $today = date('Y-m-d');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Reminder::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionNext() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $service_id = $parents[0];
                $out = Next::getNextList($service_id);

                return json_encode(['output'=>$out, 'selected'=>'']);

            }
        }
        return json_encode(['output'=>'', 'selected'=>'']);
    }

        public function actionIndextoday()
        {
          $model = new Reminder;
          $today = date('Y-m-d');

          // $expression = new Expression('NOW()');
          $searchModel = ReminderSearch::find()->andFilterWhere(['like', 'next_date', $today]);

          $dataProvider = new ActiveDataProvider(['query' =>$searchModel,
          'sort' => ['attributes' => [

                             'id' => [

                                'default' => SORT_DESC
                             ],
                        ],],

                      ]);

          if(Yii::$app->request->post('hasEditable'))
          {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            if ($model->load($post))
            {
              $value = $model->status;
              return ['output'=> $value, 'message' => ''];

            }
            else {
              return ['otuput' => '', 'message' => ''];
            }

          }

          return $this->render('indextoday', [
              'searchModel' => $searchModel,
              'dataProvider' => $dataProvider,
              'today' =>  $today,
              'model' => $model,
          ]);
        }


        public function actionIndexweek()
        {
          $model = new Reminder;
          $today = date('Y-m-d');
          $week = date('Y-m-d', strtotime("+1 week", strtotime($today)));
          $searchModel = ReminderSearch::find()->andFilterWhere(['between', 'next_date', $today, $week]);
          $dataProvider = new ActiveDataProvider(['query' =>$searchModel,
          'sort' => ['attributes' => ['id' => ['default' => SORT_DESC]]]]);
          if(Yii::$app->request->post('hasEditable'))
          {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            if ($model->load($post))
            {
              $value = $model->status;
              return ['output'=> $value, 'message' => ''];
            }
            else {
              return ['otuput' => '', 'message' => ''];
            }

          }
          return $this->render('indexweek', [
              'searchModel' => $searchModel,
              'dataProvider' => $dataProvider,
              'today' =>  $today,
              'week' =>  $week,
              'model' => $model,
          ]);
        }


        public function actionCalendar()
        {
            $searchModel = new ReminderSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $dataProvider->setSort(['defaultOrder' => ['id'=>SORT_DESC]]);
            return $this->render('calendar', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }


}

views/reminder/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use kartik\depdrop\DepDrop;
use yii\helpers\Url;

use app\models\Service;

use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Reminder */
/* @var $form yii\widgets\ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>
<div class="reminder-form">

  <table>

    <tr>

        <td class="col-md-4">

                <?= $form->field($model, 'customer')->label(false)->textInput([
                'maxlength' => true,
                'placeholder'=>'Cliente', ]) ?>
        </td>

        <td class="col-md-2">

              <?= $form->field($model, 'phone')->label(false)->textInput(['maxlength' => true,
              'placeholder'=>'Telefono',
              ]) ?>
        </td>

        <td class="col-md-3">

                <?= $form->field($model, 'car')->label(false)->textInput([
                'maxlength' => true,
                'placeholder'=>'Automóvil',
              ]) ?>
        </td>

    </tr>

  </table>

  <table>

    <tr>

        <td class="col-md-2">


              <?= $form->field($model, 'service')->label(false)->dropDownList(Service::getServices(), [
                'id'=>'service-id', 'prompt' => 'Servicio de'
              ]); ?>
        </td>

        <td class="col-md-2">


              <?= $form->field($model, 'permutation')->label(false)->widget(DepDrop::classname(), [
                  'options'=>['prompt' => 'Siguiente servicio en'],
                  // 'data' => Next::getNextList($model->service),

                  'pluginOptions'=>[
                      'depends'=>['service-id'],
                      'placeholder'=>'Siguiente servicio en',
                      'url'=>Url::to(['reminder/next'])
                  ]
              ]); ?>

        </td>

        <td class="col-md-4">

              <?= $form->field($model, 'anotation')->label(false)->textInput([
              'maxlength' => true,
              'placeholder'=>'Comentarios',
            ]) ?>
        </td>

    </tr>

  </table>

    <div class="form-group pull-right">
        <?= Html::submitButton($model->isNewRecord ? 'Registrar' : 'Modificar', ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/reminder/_form_update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use kartik\depdrop\DepDrop;
use yii\helpers\Url;

use app\models\Service;

// use yii\jui\DatePicker;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Reminder */
/* @var $form yii\widgets\ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>
<div class="reminder-form">

  <table>

    <tr>

        <td class="col-md-4">

                <?= $form->field($model, 'customer')->label(false)->textInput([
                'maxlength' => true,
                'placeholder'=>'Cliente', ]) ?>
        </td>

        <td class="col-md-2">

              <?= $form->field($model, 'phone')->label(false)->textInput(['maxlength' => true,
              'placeholder'=>'Telefono',
              ]) ?>
        </td>

        <td class="col-md-3">

                <?= $form->field($model, 'car')->label(false)->textInput([
                'maxlength' => true,
                'placeholder'=>'Automóvil',
              ]) ?>
        </td>

    </tr>

  </table>
  <table>

    <tr>

        <td class="col-md-2">


              <?= $form->field($model, 'service')->label(false)->dropDownList(Service::getServices(), [
                'id'=>'service-id', 'prompt' => 'Servicio de'
              ]); ?>
        </td>

        <td class="col-md-2">

<!--
              <?= $form->field($model, 'permutation')->label(false)->widget(DepDrop::classname(), [
                  'options'=>['prompt' => 'Siguiente servicio en'],
                  // 'data' => Next::getNextList($model->service),

                  'pluginOptions'=>[
                      'depends'=>['service-id'],
                      'placeholder'=>'Siguiente servicio en',
                      'url'=>Url::to(['reminder/next'])
                  ]
              ]); ?> -->

        </td>
    </tr>

  </table>

    <table>
      <tr>
          <td class="col-md-2">
                <?= $form->field($model, 'next_date')->widget(DatePicker::classname(), [
                  'options' => ['placeholder' => 'Siguiente Servicio'],
                  'pluginOptions' => [
                      'autoclose'=>true,
                      'format' => 'yyyy-mm-dd'
                  ]
              ]); ?>
          </td>
          <td class="col-md-4">
                <?= $form->field($model, 'anotation')->label(false)->textInput([
                'maxlength' => true,
                'placeholder'=>'Comentarios',
              ]) ?>
          </td>
      </tr>
    </table>

    <div class="form-group pull-right">
        <?= Html::submitButton($model->isNewRecord ? 'Registrar' : 'Modificar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/reminder/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ReminderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reminder-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'customer') ?>

    <?= $form->field($model, 'car') ?>

    <?= $form->field($model, 'phone') ?>

    <?= $form->field($model, 'service') ?>

    <?php // echo $form->field($model, 'date') ?>

    <?php // echo $form->field($model, 'next_date') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/reminder/calendar.php
<?php

use yii\helpers\Html;
// use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\grid\GridView;
use marekpetras\calendarview\CalendarView;


/* @var $this yii\web\View */
/* @var $searchModel app\models\ReminderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
//
// $this->title = 'Reminders';
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="reminder-index">
<div class="pull-right">
    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
  </div>
<?= CalendarView::widget(
    [
        // mandatory
        'dataProvider'  => $dataProvider,
        'dateField'     => 'next_date',
        'valueField'    => 'customer',


        // optional params with their defaults
        'weekStart' => 1, // date('w') // which day to display first in the calendar
        'title'     => '',

        'views'     => [
            'calendar' => '@vendor/marekpetras/yii2-calendarview-widget/views/calendar',
            'month' => '@vendor/marekpetras/yii2-calendarview-widget/views/month',
            'day' => '@vendor/marekpetras/yii2-calendarview-widget/views/day',
        ],

        'startYear' => date('Y') - 1,
        'endYear' => date('Y') + 1,

        // 'link' => true,
        //  alternates to link , is called on every models valueField, used in Html::a( valueField , link )
        'link' => 'site/view',
        'link' => function($model,$calendar){
            return ['view','id'=>$model->id];
        },


        'dayRender' => false,
        /* alternate to dayRender
        'dayRender' => function($model,$calendar) {
            return '<p>'.$model->id.'</p>';
        },
        */

    ]
);?>

</div>

views/reminder/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Reminder */
//
// $this->title = 'Create Reminder';
// $this->params['breadcrumbs'][] = ['label' => 'Reminders', 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="reminder-create">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/reminder/index.php
<?php

use yii\helpers\Html;
// use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ReminderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
//
// $this->title = 'Reminders';
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="reminder-index">
<div class="pull-right">
    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Registrar Servicio', ['create'], ['class' => 'btn btn-default']) ?>
    </p>
  </div>


<?php $gridColumns =  [


      [
        'attribute'=>'date',
        'vAlign'=>'middle',
        'hAlign'=>'right',
        'label' => 'Fecha del Servicio',
        'width'=>'9%',
        'format'=>'date',
        'pageSummary'=>false
      ],
    [
    'attribute'=>'customer',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Cliente',

    ],
    [
    'attribute'=>'phone',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Teléfono',

    ],
    [
    'attribute'=>'car',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Automóvil',

    ],
    [
    'attribute'=>'service',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Servicio',
    'value' => function ($model) {
          if ($model->service == 1) {return 'Cambio de Aceite';}
          if ($model->service == 2) {return 'Afinación';}
          if ($model->service == 3) {return 'Lavado de Inyectores';}
    }

    ],
    [
    'attribute'=>'anotation',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Comentarios',

    ],

    [
      'attribute'=>'next_date',
      'vAlign'=>'middle',
      'hAlign'=>'right',
      'width'=>'9%',
      'format'=>'date',
      'pageSummary'=>false,
      'label' => 'Siguiente Servicio',

    ],

    [
              'class' => 'kartik\grid\ActionColumn',
              'header'=>false,
              // 'pageSummary' => false,
              'options'=>['style'=>'width:150px;'],
              'buttonOptions'=>['class'=>'btn btn-default'],
              'template'=>'{view}',
              'buttons'=>[

                'view'=> function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-plus"></span>', $url, [
                                        'title' => Yii::t('yii', 'Viewtoday'),
                                ]);
                              }
              ]
            ],

]?>

<?= GridView::widget([
    'dataProvider'=>$dataProvider,
    'filterModel'=>$searchModel,
    'columns'=>$gridColumns,

    // 'containerOptions'=>['style'=>'overflow: auto'], // only set when $responsive = false
    // 'headerRowOptions'=>['class'=>'kartik-sheet-style'],
    // 'filterRowOptions'=>['class'=>'kartik-sheet-style'],
    'pjax'=>true, // pjax is set to always true for this demo
    // set your toolbar
    'export' => false,
    'toggleData' => false,
    // parameters from the demo form
    'bordered'=>false,
    'striped'=>true,
    // 'condensed'=>true,
    'responsive'=>true,
    'hover'=>false,
    'summary' => false,
    'showPageSummary'=>false,
    'panel'=>[
        'type'=>GridView::TYPE_INFO,
        'heading'=>'Servicios Registrados',
    ],
    'persistResize'=>true,
    // 'toggleDataOptions'=>['minCount'=>10],
]);?>

</div>

views/reminder/indextoday.php
<?php
use yii\helpers\Html;
// use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
// use app\models\Status;
use app\models\Reminder;
use app\models\ReminderSearch;

?>
<?php
?>
<?php $tituloexport = 'Recordatorios para hoy: '.$today?>
<?php $this->title = $tituloexport?>
<div class="reminder-indextoday">

<?php $gridColumns =  [
    [
    'attribute'=>'customer',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Cliente',

    ],
    [
    'attribute'=>'phone',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Teléfono',

    ],
    [
    'attribute'=>'car',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Automóvil',

    ],
    [
    'attribute'=>'service',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Servicio',
    'value' => function ($model) {
          if ($model->service == 1) {return 'Cambio de Aceite';}
          if ($model->service == 2) {return 'Afinación';}
          if ($model->service == 3) {return 'Lavado de Inyectores';}
    }

    ],
    [
    'attribute'=>'anotation',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Comentarios',

    ],

    [
      'attribute'=>'date',
      'vAlign'=>'middle',
      'hAlign'=>'right',
      'label' => 'Servicio Anterior',
      'width'=>'9%',
      'format'=>'date',
      'pageSummary'=>false
    ],

    [
              'class' => 'kartik\grid\ActionColumn',
              'header'=>false,
              // 'pageSummary' => false,
              'options'=>['style'=>'width:150px;'],
              'buttonOptions'=>['class'=>'btn btn-default'],
              'template'=>'{view}',
              'buttons'=>[

                'view'=> function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-plus"></span>', $url, [
                                        'title' => Yii::t('yii', 'Viewtoday'),
                                ]);
                              }
              ]
            ],

]?>

<?= GridView::widget([
    'dataProvider'=>$dataProvider,
    'filterModel'=>$searchModel,
    'columns'=>$gridColumns,

    // 'containerOptions'=>['style'=>'overflow: auto'], // only set when $responsive = false
    // 'headerRowOptions'=>['class'=>'kartik-sheet-style'],
    // 'filterRowOptions'=>['class'=>'kartik-sheet-style'],
    'pjax'=>true, // pjax is set to always true for this demo
    // set your toolbar
    'export' => false,
    'toggleData' => false,
    // parameters from the demo form
    'bordered'=>false,
    'striped'=>true,
    // 'condensed'=>true,
    'responsive'=>true,
    'hover'=>false,
    'showPageSummary'=>false,
    'panel'=>[
        'type'=>GridView::TYPE_PRIMARY,
        'heading'=>'Recordatorios para hoy: '.$today,
    ],
    'persistResize'=>true,
    // 'toggleDataOptions'=>['minCount'=>10],
]);?>

</div>

views/reminder/indexweek.php
<?php
use yii\helpers\Html;
// use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
// use app\models\Status;
use app\models\Reminder;
use app\models\ReminderSearch;

?>
<?php $tituloexport = 'Recordatorios de los siguientes 7 dias: '.$today?>
<?php $this->title = $tituloexport?>
<div class="reminder-indextoday">

<?php $gridColumns =  [
    [
      'attribute'=>'next_date',
      'vAlign'=>'middle',
      'hAlign'=>'right',
      'width'=>'9%',
      'format'=>'date',
      'pageSummary'=>false
    ],
    [
    'attribute'=>'customer',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Cliente',

    ],
    [
    'attribute'=>'phone',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Teléfono',

    ],
    [
    'attribute'=>'car',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Automóvil',

    ],
    [
    'attribute'=>'service',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Servicio',
    'value' => function ($model) {
          if ($model->service == 1) {return 'Cambio de Aceite';}
          if ($model->service == 2) {return 'Afinación';}
          if ($model->service == 3) {return 'Lavado de Inyectores';}
    }
    ],
    [
    'attribute'=>'anotation',
    'width'=>'310px',
    'pageSummary'=>false,
    'label' => 'Comentarios',

    ],

    [
      'attribute'=>'date',
      'vAlign'=>'middle',
      'hAlign'=>'right',
      'label' => 'Servicio Anterior',
      'width'=>'9%',
      'format'=>'date',
      'pageSummary'=>false
    ],

    [
              'class' => 'kartik\grid\ActionColumn',
              'header'=>false,
              // 'pageSummary' => false,
              'options'=>['style'=>'width:150px;'],
              'buttonOptions'=>['class'=>'btn btn-default'],
              'template'=>'{view}',
              'buttons'=>[

                'view'=> function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-plus"></span>', $url, [
                                        'title' => Yii::t('yii', 'Viewtoday'),
                                ]);
                              }
              ]
            ],

]?>

<?= GridView::widget([
    'dataProvider'=>$dataProvider,
    'filterModel'=>$searchModel,
    'columns'=>$gridColumns,
    // 'containerOptions'=>['style'=>'overflow: auto'], // only set when $responsive = false
    // 'headerRowOptions'=>['class'=>'kartik-sheet-style'],
    // 'filterRowOptions'=>['class'=>'kartik-sheet-style'],
    'pjax'=>true, // pjax is set to always true for this demo
    // set your toolbar
    'export' => false,
    'toggleData' => false,
    // parameters from the demo form
    'bordered'=>false,
    'striped'=>true,
    // 'condensed'=>true,
    'responsive'=>true,
    'hover'=>false,
    'showPageSummary'=>false,
    'panel'=>[
        'type'=>GridView::TYPE_DEFAULT,
        'heading'=>'Recordatorios de la Semana',
    ],
    'persistResize'=>true,
    // 'toggleDataOptions'=>['minCount'=>10],
]);?>

</div>

views/reminder/update.php
<?php

use yii\helpers\Html;
//
// $this->title = 'Update Reminder: ' . $model->id;
// $this->params['breadcrumbs'][] = ['label' => 'Reminders', 'url' => ['index']];
// $this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
// $this->params['breadcrumbs'][] = 'Update';
?>
<div class="reminder-update">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form_update', [
        'model' => $model,
    ]) ?>

</div>

views/reminder/view.php
<?php

use yii\helpers\Html;
// use yii\widgets\DetailView;
use kartik\detail\DetailView;
use yii2assets\printthis\PrintThis;

// $this->title = $model->id;
// $this->params['breadcrumbs'][] = ['label' => 'Reminders', 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="reminder-view">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

<?php
    if ($model->service == 1) {$service = 'Cambio de Aceite';}
    if ($model->service == 2) {$service = 'Afinación';}
    if ($model->service == 3) {$service = 'Lavado de Inyectores';}
?>


    <?= DetailView::widget([
        'model' => $model,
        'mode'=> 'view',
        'bordered' => false,
        'striped' => true,
        'condensed' => false,
        'responsive' => true,
        'hover' => false,
        'bootstrap' => true,
        'attributes' => [
            // 'id',
            'customer',
            'car',
            'phone',
            ['attribute' => 'service',
            'value' => $service,
            ],

            'anotation',
            ['attribute' => 'date', 'format' => 'date'],
            ['attribute' => 'next_date', 'format' => 'date'],

            // 'permutation',
            // 'test',
        ],
    ]) ?>

    <p class="pull-right">
      <?= Html::a('Modificar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
      <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
        'class' => 'btn btn-danger',
        'data' => [
          'confirm' => 'Seguro que desea eliminar esto?',
          'method' => 'post',
        ],
        ]) ?>
      </p>

</div>
<div style="display: none;">
<div id="PrintThis">


<table>
  <tr>
    <td>
<div class="col-md-4" >
  <h2> REFACCIONARIA Y SERVICIOS JUÁREZ</h2>
</div>
    </td>
    <td>
<div class="col-md-2">
  <img style="width:64px" src="/img/logo.jpg">
</div>
    </td>
  </tr>
  <tr>
    <td>
<div style="text-align:center">
<h3> Tels: 323 1223 , 312 143 5680, 312 165 0313</h3>
</div>
    </td>
  </tr>
</table>
      <?= DetailView::widget([
          'model' => $model,
          'labelColOptions' => ['style' => 'width:30%'],
          'mode'=> 'view',
          'bordered' => false,
          'striped' => true,
          'condensed' => true,
          'responsive' => true,
          'hover' => true,
          'bootstrap' => true,
          'hAlign' => 'right',
          'attributes' => [
              // 'id',
              // 'customer',
              'car',
              // 'phone',
              ['attribute' => 'service',
              'value' => $service,
              ],
              ['attribute' => 'anotation', 'label' => 'Anotaciones'],
              ['attribute' => 'date', 'format' => 'date', 'label' => 'Fecha del Último Servicio'],
              ['attribute' => 'next_date', 'format' => 'date', 'label' => 'Fecha del Siguiente Servicio'],
          ],
      ]) ?>
</div>
</div>


<?php
echo PrintThis::widget([
	'htmlOptions' => [
		'id' => 'PrintThis',
		'btnClass' => 'btn btn-info',
		'btnId' => 'btnPrintThis',
		'btnText' => 'Imprimir',
		'btnIcon' => 'fa fa-print'
	],
	'options' => [
		'debug' => false,
		'importCSS' => true,
		'importStyle' => false,
		// 'loadCSS' => "path/to/my.css",
		'pageTitle' => "",
		'removeInline' => false,
		'printDelay' => 333,
		'header' => null,
		'formValues' => true,
	]
]);
?>